# Generated by Django 5.2.10 on 2026-01-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university_id', models.IntegerField(unique=True)),
                ('national_id', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('image', models.ImageField(upload_to='student_images/')),
            ],
        ),
    ]
